# yaml-language-server: $schema=https://json.schemastore.org/lefthook.json
assert_lefthook_installed: true
commit-msg:
  commands:
    commitlint:
      run: grep -q "^fixup! " "{1}" || commitlint lint --message "{1}"
    trailers:
      run: git interpret-trailers --in-place --trailer "sign" --trim-empty "{1}"
pre-commit:
  piped: true
  commands:
    go:fix:
      priority: 1
      run: task go:fix {staged_files}
      glob: "**/*.go"
      stage_fixed: true
    typos:lint:
      priority: 1
      run: typos --force-exclude {staged_files}
      exclude: .*\.(jpg|png)$
    task:lint:
      priority: 1
      run: task -a -j > /dev/null
      glob: Taskfile.yaml
    editorconfig:lint:
      priority: 1
      run: editorconfig-checker ${ARGS} {staged_files}
      env:
        ARGS: ""
      exclude: .*\.(jpg|png)$
    ## TODO XML/HTML lint
    # gofumpt:
    #   priority: 1
    #   run: gofumpt -l -w {staged_files}
    #   glob: "**/*.go"
    #   stage_fixed: true
    markdown:lint:
      priority: 10
      run: task markdown:lint
      glob: "**/*.md"
    go:lint:
      priority: 10
      run: task go:lint
      glob: "**/*.go"
    go:tidy:
      priority: 40
      run: task go:tidy
      glob: "{**/*.go,go.mod}"
      stage_fixed: true
pre-push:
  piped: true
  commands:
    build:
      priority: 50
      run: task build
      glob: "{**/*.go,go.mod,go.sum}"
    test:
      priority: 50
      run: task test
      glob: "{**/*.go,go.mod,go.sum}"
skip_output:
- meta
# - summary
# - skips
